#!/usr/bin/env sh

if ! [ -x "$(command -v stern)" ]; then
  echo 'Error: stern is not installed.' >&2
  exit 1
fi

if ! [ -x "$(command -v jq)" ]; then
  echo 'Error: jq is not installed.' >&2
  exit 1
fi

if [ -z "$1" ]; then
  echo "Arguments are missing. Command should be used with 2 arguments, like: sternjson <app-name> <?filter>"
  exit 1
fi

appName=$1

if [ -z "$2" ]; then
    stern -o json "${appName}" | jq -R "fromjson? | .message|fromjson"
else
    filter=$2
    stern -o json "${appName}" | jq -R "fromjson? | .message|fromjson | ${filter}"
fi
